version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

executors:
  default:
    docker:
      - image: cimg/node:20.12.1

commands:
  install-dependencies:
    steps:
      - run: cd ./infrastructure && npm install .
  cache-dependencies:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./infrastructure/node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  build-app:
    steps:
      - run: cd ./infrastructure && npm run build
  deploy-app:
    steps:
      - run:
          name: List build directory
          command: cd ./infrastructure && ls -la /home/circleci/project
      - run:
          name: Deploy
          command: cd ./infrastructure && npm run deploy

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - build-app

  deploy:
    executor: aws-cli/default
    resource_class: small
    steps:
      - checkout
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          context: aws-account
          requires:
            - build
          filters:
            branches:
              only:
                - main
